.TH pantheon-photos-video-thumbnailer 1 "August 21, 2011"
.SH NAME
pantheon-photos-video-thumbnailer \- writes video thumbnail to stdout
.SH DESCRIPTION
Writes video thumbnail to stdout.
.PP
This program is designed to be called by pantheon-photos directly, normally it is not
of any use for pantheon-photos users.
.SH COPYRIGHT
This manual page is Copyright 2011 Luca Falavigna <dktrkranz@debian.org>.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Lesser General Public License, Version 2.1 or any
later version published by the Free Software Foundation.
