.TH io.elementary.photos 1 "December 30, 2009"
.SH NAME
photos \- a digital photo organizer
.SH DESCRIPTION
.B photos
is a digital photo organizer designed for elementary's Pantheon desktop environment. It
allows you to import photos from disk or camera, organize them in various ways,
view them in full-window or fullscreen mode, and export them to share with
others.
.SH AUTHOR
shotwell was written by Jim Nelson, Lucas Beeler and Allison Barlow.
.PP
This manual page was written by Devid Antonio Filoni <d.filoni@ubuntu.com>,
for the Debian project (and may be used by others).
