
#define _PREFIX "@CMAKE_INSTALL_PREFIX@"
#define _VERSION "@VERSION@"
#define GETTEXT_PACKAGE "@GETTEXT_PACKAGE@"
#define _LIB "@CMAKE_INSTALL_FULL_LIBDIR@"
#define _LIBEXECDIR "@CMAKE_INSTALL_FULL_LIBEXECDIR@/@CMAKE_PROJECT_NAME@"
#define _LANG_SUPPORT_DIR "@CMAKE_INSTALL_PREFIX@/share/locale"
